### ISSUE TITLE
[CheckList] Representation

### ISSUE THREAD

**Issue by guilyx** [Guilyx/autonomous-uav#1]
- [x] Geodetic Frame (Longitude, Latitude, Altitude - Global Position )
- [x] ECEF Frame ( NED - Local Position )
- [ ] Body Frame
- [x] Euler Rotation Matrices
- [x] Quaternion
- [x] Motions as Transformations
- [x] Configuration Space

**Comment by guilyx** [comment]
Checked : Euler rotation matrices
